name: install-testing
on: push

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2 
      - name: Install all dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest

